name: Tests

on: [push]

jobs:
  tests:
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/cache@v2
        name: Configure poetry caching
        with:
          path: ~/.cache/poetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/setup.py') }}
          restore-keys: |
            ${{ runner.os }}-poetry-
      - name: Install Python dependencies
        run: |
          python -m pip install poetry
          poetry install
      - name: Run tests
        run: |
          poetry run pytest -v